const ActionTypes = {
    LOADER: 'LOADER',
    SHOWERROR: 'SHOWERROR',
    HIDEERROR: 'HIDEERROR',
    USERNAME: 'USERNAME',
    CURRENTUSER: 'CURRENTUSER',
    ALLUSERS: 'ALLUSERS',
    USERINFO: 'USERINFO',
    // SHOWLOADER: 'SHOWLOADER',
    // HIDELOADER: 'HIDELOADER',
    // ISLOGGEDIN: 'ISLOGGEDIN',
    COUPONS : 'COUPONS',
    WALLET : 'WALLET',
    USERDETAILS:"USERDETAILS",
    USEDCOUPONS:"USEDCOUPONS"
}

export default ActionTypes;